name: Get V2Ray latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
  watch:
    types: [started]
jobs:
  get-version:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch V2Ray release version
        run: |
          curl -sL https://api.github.com/repos/v2fly/v2ray-core/releases/latest | \
          jq -r ".tag_name" > v2ray-core-version
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email 50695187+tr1s7an@users.noreply.github.com
          git config --global user.name tr1s7an
          git add .
          git commit -m "New release version"
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main